# SHOW ME your WORK 💪

# Problem statement
"Trips & Travel.Com" company wants to enable and establish a viable business model to expand the customer base. One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering * Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information. The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being. However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient

# Data Collection
The Dataset is collected from https://www.kaggle.com/datasets/susant4learning/holiday-package-purchase-prediction The data consists of 20 column and 4888 rows.

In [28]:
# import libraries
import pandas as pd
import numpy as np

In [29]:
# read the data
df = pd.read_csv(r"D:\GitHub\CS-IEEE-ZSB-26-AI\Task7\Travel.csv")
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

## Data Cleaning

In [30]:
df.drop("CustomerID", axis=1, inplace=True)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ProdTaken                 4888 non-null   int64
 1   Age                       4662 non-null   float64
 2   TypeofContact             4863 non-null   object
 3   CityTier                  4888 non-null   int64
 4   DurationOfPitch           4637 non-null   float64
 5   Occupation                4888 non-null   object
 6   Gender                    4888 non-null   object
 7   NumberOfPersonVisiting    4888 non-null   int64
 8   NumberOfFollowups         4843 non-null   float64
 9   ProductPitched            4888 non-null   object
 10  PreferredPropertyStar     4862 non-null   float64
 11  MaritalStatus             4888 non-null   object
 12  NumberOfTrips             4748 non-null   float64
 13  Passport                  4888 non-null   int64
 14  PitchSatisfactionScore    4888 non-null   int64
 15  OwnCar                    4888 non-null   int64
 16  NumberOfChildrenVisiting  4822 non-null   float64
 17  Designation               4888 non-null   object
 18  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(6), object(6)
memory usage: 725.7+ KB

In [32]:
df.isnull().sum()

ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [33]:
num_cols = df.select_dtypes(include='number').columns
cat_cols = df.select_dtypes(exclude='number').columns

df[num_cols] = df[num_cols].fillna(df[num_cols].median())
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

In [34]:
df[cat_cols].value_counts()

TypeofContact    Occupation      Gender   ProductPitched  MaritalStatus  Designation
Self Enquiry     Salaried        Male     Basic           Married        Executive         188
                 Small Business  Male     Deluxe          Married        Manager           179
                 Salaried        Male     Deluxe          Married        Manager           138
                 Small Business  Male     Basic           Married        Executive         132
                                 Female   Deluxe          Married        Manager           125
                                                                                          ...
Company Invited  Large Business  Female   Basic           Unmarried      Executive           1
                                 Fe Male  Basic           Unmarried      Executive           1
Self Enquiry     Large Business  Fe Male  Super Deluxe    Unmarried      AVP                 1
                 Salaried        Fe Male  Standard        Single         Senior Manager      1
                 Small Business  Male     Super Deluxe    Unmarried      AVP                 1
Name: count, Length: 211, dtype: int64

In [35]:
df['Gender'] = df['Gender'].replace('Fe Male', 'Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single', 'Unmarried')

In [36]:
df[['Gender', 'MaritalStatus']].value_counts()

Gender  MaritalStatus
Male    Married          1444
        Unmarried         908
Female  Married           896
        Unmarried         690
Male    Divorced          564
Female  Divorced          386
Name: count, dtype: int64

## Feature Engineering & Encoding

In [38]:
df['TotalVisiting'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']

df.drop(columns=['NumberOfPersonVisiting', 'NumberOfChildrenVisiting'], axis=1, inplace=True)

df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [40]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,1,3,6.0,2,0,3.0,1,3.0,2,1.0,1,2,1,2,20993.0,3.0
1,0,49.0,0,1,14.0,2,1,4.0,1,4.0,0,2.0,0,3,1,2,20130.0,5.0
2,1,37.0,1,1,8.0,0,1,4.0,0,3.0,2,7.0,1,3,0,1,17090.0,3.0
3,0,33.0,0,1,9.0,2,0,3.0,0,3.0,0,2.0,1,5,1,1,17909.0,3.0
4,0,36.0,1,1,8.0,3,1,3.0,0,4.0,0,1.0,0,5,1,1,18468.0,2.0

#### Splitting the data

In [41]:
X = df.drop("ProdTaken", axis=1)
y = df["ProdTaken"]

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#### Scaling the data

In [43]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#### Build a classification model using support vector machine. Use standalone model as well as Bagging model and check if you see any difference in the performance.

In [44]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svm = SVC()

svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)

print(accuracy_score(y_test, y_pred))

0.8660531697341514

In [45]:
from sklearn.ensemble import BaggingClassifier

bag_svm = BaggingClassifier(
    estimator=SVC(),
    n_estimators=10,
    random_state=42
)

bag_svm.fit(X_train, y_train)

y_pred = bag_svm.predict(X_test)

print(accuracy_score(y_test, y_pred))

0.8680981595092024

#### Now use decision tree classifier. Use standalone model as well as Bagging and check if you notice any difference in performance

In [46]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)

print(accuracy_score(y_test, y_pred))

0.9192229038854806

In [48]:
bag_dt = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=10,
    random_state=42
)

bag_dt.fit(X_train, y_train)

y_pred = bag_dt.predict(X_test)

print(accuracy_score(y_test, y_pred))

0.9314928425357873

#### then use random forest classifier. Use standalone model as well as Bagging and check if you notice any difference in performance

In [49]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print(accuracy_score(y_test, y_pred))

0.9294478527607362

In [50]:
bag_rf = BaggingClassifier(
    estimator=RandomForestClassifier(),
    n_estimators=10,
    random_state=42
)

bag_rf.fit(X_train, y_train)

y_pred = bag_rf.predict(X_test)

print(accuracy_score(y_test, y_pred))

0.908997955010225

#### Comparing performance of them to figure out where it makes most sense to use bagging and why. What conditions bagging works the best.

In [53]:
'''''
SVM: 
bagging adds a little because the model is low variance, so we use it when the model is heigh variance.

DS:
bagging adds more because the model is heigh variance, so it reduces the overfitting.

RF:
The accuracy drops because RF is already an ensample of trees using bagging, so bagging the model again increase the randomness and it can reduce the performance.
'''''

"''\nSVM: \nbagging adds a little because the model is low variance, so we use it when the model is heigh variance.\n\nDS:\nbagging adds more because the model is heigh variance, so it reduces the overfitting.\n\nRF:\nThe accuracy drops because RF is already an ensample of trees using bagging, so bagging the model again increase the randomness and it can reduce the performance.\n"